language: scala
jdk:
  - openjdk11
scala:
  - 2.12.10
script:
  - sbt ++$TRAVIS_SCALA_VERSION test

cache:
  directories:
    - "$HOME/.cache/coursier/v1"
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/boot"