language: scala
jdk:
  - openjdk11
scala:
  - 2.12.10
services:
  - docker

script:
  - echo "echo $STEWARD_PASS" >pass.sh
  - chmod u+x pass.sh
  - docker run -v $STEWARD_DIR:/opt/scala-steward -it fthomas/scala-steward:latest \
    --workspace  "/opt/scala-steward/workspace" \
    --repos-file "/opt/scala-steward/repos.md" \
    --git-author-email $ST_EMAIL \
    --vcs-api-host "https://api.github.com" \
    --vcs-login $ST_LOGIN \
    --git-ask-pass "pass.sh" \
    --sign-commits