language: scala
jdk:
  - openjdk11
scala:
  - 2.12.10
script:
  - sbt ++$TRAVIS_SCALA_VERSION validate

cache:
  directories:
    - "$HOME/.cache/coursier/v1"
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/boot"
after_success:
  - bash <(curl -s https://codecov.io/bash) -t CODECOV_TOKEN