CREATE TABLE IF NOT EXISTS ITEM(
    ID VARCHAR(40) NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    PRICE DECIMAL NOT NULL,
    CATEGORY VARCHAR(20) NOT NULL,
    PRIMARY KEY(ID)
);