addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.4.1")
addSbtPlugin("de.heikoseeberger" % "sbt-header" % "5.3.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.1.8")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.2.1")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.6.1")
addSbtPlugin("org.wartremover" % "sbt-wartremover" % "2.4.3")
addSbtPlugin("org.lyranthe.fs2-grpc" % "sbt-java-gen" % "0.5.4")
addSbtPlugin("com.github.mwz" % "sbt-sonar" % "2.1.0")