name: "Continuos integration pipeline for scala projects"

on:
  push:
      branches:
          - master
          - develop
  pull_request:
      branches:
          - master
          - develop
  
jobs:
    test:
      runs-on: ubuntu-18.04
      steps:
          - uses: actions/checkout@v2
          - name: Run test
            run: sbt validate

