name: "Continuos integration pipeline for scala projects"

on:
  push:
      branches:
          - master
          - develop
  pull_request:
      branches:
          - master
          - develop

jobs:
    test:
      runs-on: ubuntu-18.04
      steps:
          - uses: actions/checkout@v2
          - name: Run test
            run: sbt validate
    build:
      runs-on: ubuntu-18.04
      steps:
          - uses: actions/checkout@v2
          - name: Auth image registry
            run: echo "${{ secrets.DOCKERPW }}" | docker login -u gsissa --password-stdin
          - name: make docker file
            run: sbt grpc/docker:stage
          - name: Build image && push
            env:
              BASE_IMAGE_TAG: ${{ secrets.DOCKER_REGISTRY }}/$GITHUB_REPOSITORY:$GITHUB_REF_NAME_SLUG
            run: |
              cd grpc/target/docker/stage              
              docker image build -t $BASE_IMAGE_TAG-$GITHUB_SHA_SHORT .
              docker image build -t $BASE_IMAGE_TAG-latest .
              docker push $BASE_IMAGE_TAG-$GITHUB_SHA_SHORT
              docker push $BASE_IMAGE_TAG-latest



