name: "Continuos integration pipeline for scala projects"

on:
  push:
      branches:
          - master
          - develop
  pull_request:
      branches:
          - master
          - develop

jobs:
    test:
      runs-on: ubuntu-18.04
      steps:
          - uses: actions/checkout@v2
          - name: Run test
            run: sbt validate
    build:
      needs: test
      runs-on: ubuntu-18.04
      steps:
          - uses: actions/checkout@v2
          - name: Auth image registry
            run: echo "${{ secrets.DOCKERPW }}" | docker login  ${{ secrets.DOCKER_REGISTRY }} -u gsissa --password-stdin
          - name: make docker file
            run: sbt grpc/docker:stage
          - name: Build image && push            
            run: |
              cd grpc/target/docker/stage
              GIT_HASH=$(git rev-parse --short "$GITHUB_SHA")
              GIT_BRANCH=${GITHUB_REF##*/}
              PROJECT=${GITHUB_REPOSITORY##*/}
              BASE_IMAGE_TAG=${{ secrets.DOCKER_REGISTRY }}/${PROJECT}:${GIT_BRANCH}
              LATEST_IMG=$BASE_IMAGE_TAG-latest
              SHA_IMG=$BASE_IMAGE_TAG-${GIT_HASH}
              docker image build -t $SHA_IMG .
              docker tag $SHA_IMG $LATEST_IMG
              docker push $SHA_IMG
              docker push $LATEST_IMG
              echo "==============================="
              echo "images tagged:"
              echo $LATEST_IMG
              echo $SHA_IMG
              echo "==============================="
    deploy:
      # needs: build
      runs-on: ubuntu-18.04
      steps:
          - uses: actions/checkout@v2
            with: 
              repositoy: Kitsmile/ks-manifest
              ssh-key: ${{ secrets.CI_SSH_KEY }}
              persist-credentials: false
          - name: get manifest files
            run: |
              ls
              cd 
              ls              
              git version
              git clone git@github.com:KitSmile/ks-manifest.git
              ls


