name: "Continuos integration pipeline for scala projects"

on:
  push:
      branches:
          - master
          - develop
  pull_request:
      branches:
          - master
          - develop

jobs:
    test:
      runs-on: ubuntu-18.04
      steps:
          - uses: actions/checkout@v2
          - name: Run test
            run: sbt validate
    build:
      # needs: test
      runs-on: ubuntu-18.04
      steps:
          - uses: actions/checkout@v2
          - name: Auth image registry
            run: echo "${{ secrets.DOCKERPW }}" | docker login  ${{ secrets.DOCKER_REGISTRY }} -u gsissa --password-stdin
          - name: make docker file
            run: sbt grpc/docker:stage
          - name: Build image && push            
            run: |
              cd grpc/target/docker/stage
              BASE_IMAGE_TAG=${{ secrets.DOCKER_REGISTRY }}/${{ env.GITHUB_REPOSITORY }}:${{ env.GITHUB_REF_NAME_SLUG }}
              echo $BASE_IMAGE_TAG
              docker image build -t $BASE_IMAGE_TAG-$GITHUB_SHA_SHORT .
              docker image build -t $BASE_IMAGE_TAG-latest .
              docker push $BASE_IMAGE_TAG-$GITHUB_SHA_SHORT
              docker push $BASE_IMAGE_TAG-latest



